apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: todo-app
spec:
  selector:
    # Selector for Pods
    app: todo-app
  ports:
    # Port Map
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
